#!/bin/sh
set -eu

if ! command -v herdr >/dev/null 2>&1; then
    exit 0
fi

# Herdr plugin manifests build below their own checkout. Do not redirect those
# artifacts into the shared Cargo target directory.
unset CARGO_TARGET_DIR

plugin_list="$(herdr plugin list)"
old_plugin="herdr-plugin-renamer"
title_plugin="herdr-plugin-agent-title"

# The old renamer generated an English slug with another Codex call and kept a
# permanent done marker per pane, so a second agent session in the same pane was
# never renamed. Use the titles already generated by Claude Code and Codex.
if printf '%s\n' "$plugin_list" | grep -Fq "$old_plugin"; then
    herdr plugin uninstall "$old_plugin"
fi

if ! printf '%s\n' "$plugin_list" | grep -Fq "$title_plugin"; then
    herdr plugin install oyoshot/herdr-plugin-agent-title --yes
fi

integration_status="$(herdr integration status)"

for agent in codex claude; do
    if ! printf '%s\n' "$integration_status" |
        grep -Eq "^${agent}: (installed|current) \("; then
        herdr integration install "$agent"
    fi
done
