name: Mac Setup
description: Restore caches, install pinned chezmoi, and apply dotfiles

inputs:
  brewfile-path:
    description: "Path to Brewfile"
    default: dot_config/homebrew/Brewfile
  mise-config-path:
    description: "Path to mise config"
    default: dot_config/mise/config.toml
  cache-epoch:
    description: "Cache generation identifier"
    required: true
  warm-mode:
    description: "Whether this run is a warm-cache job"
    default: "false"
  chezmoi-version:
    description: "Pinned chezmoi version"
    default: "2.69.3"

runs:
  using: composite
  steps:
    - id: brew-cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: macos-brew-v3-${{ hashFiles(inputs.brewfile-path) }}-${{ inputs.cache-epoch }}
        restore-keys: |
          macos-brew-v3-${{ hashFiles(inputs.brewfile-path) }}-
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/Cellar

    - id: mise-cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: macos-mise-v3-${{ hashFiles(inputs.mise-config-path) }}-${{ inputs.cache-epoch }}
        restore-keys: |
          macos-mise-v3-${{ hashFiles(inputs.mise-config-path) }}-
        path: |
          ~/.cache/mise
          ~/.local/share/mise

    - name: Install pinned chezmoi
      shell: bash
      run: |
        set -euo pipefail
        version="${{ inputs.chezmoi-version }}"
        archive="chezmoi_${version}_darwin_arm64.tar.gz"
        checksums="chezmoi_${version}_checksums.txt"

        tmpdir="$(mktemp -d)"
        trap 'rm -rf "${tmpdir}"' EXIT

        curl -fsSLo "${tmpdir}/${archive}" "https://github.com/twpayne/chezmoi/releases/download/v${version}/${archive}"
        curl -fsSLo "${tmpdir}/${checksums}" "https://github.com/twpayne/chezmoi/releases/download/v${version}/${checksums}"

        grep "  ${archive}$" "${tmpdir}/${checksums}" | (cd "${tmpdir}" && shasum -a 256 -c -)
        tar -xzf "${tmpdir}/${archive}" -C "${tmpdir}" chezmoi

        sudo install -m 0755 "${tmpdir}/chezmoi" /usr/local/bin/chezmoi
        chezmoi --version

    - name: Apply dotfiles with chezmoi
      shell: bash
      run: |
        set -euo pipefail
        chezmoi init --apply -S "${{ github.workspace }}"

    - name: Trim caches (warm mode)
      if: inputs.warm-mode == 'true'
      shell: bash
      run: |
        set -euo pipefail
        brew cleanup -s || true
        if command -v mise >/dev/null 2>&1; then
          mise cache clear || true
        fi
