name: Arch Linux Setup
description: Bootstrap Arch environment, restore caches, install pinned chezmoi, and apply dotfiles

inputs:
  arch-extra-packages-path:
    description: "Path to Arch extra packages list"
    default: dot_config/yay/extra-packages
  mise-config-path:
    description: "Path to mise config"
    default: dot_config/mise/config.toml
  cache-epoch:
    description: "Cache generation identifier"
    required: true
  warm-mode:
    description: "Whether this run is a warm-cache job"
    default: "false"
  chezmoi-version:
    description: "Pinned chezmoi version"
    required: true
  github-token:
    description: "GitHub token passed only to chezmoi apply step"
    default: ""

runs:
  using: composite
  steps:
    - name: Validate mounted cache volumes
      shell: bash
      run: |
        set -euo pipefail
        required_paths=(
          /var/cache/pacman/pkg
          /home/builder/.cache/yay
          /home/builder/.local/share/mise
          /home/builder/.local/state/mise
        )
        for p in "${required_paths[@]}"; do
          if [[ ! -d "${p}" ]]; then
            echo "Required cache mount is missing: ${p}" >&2
            exit 1
          fi
          if ! awk -v mp="${p}" '$5 == mp { found=1 } END { exit !found }' /proc/self/mountinfo; then
            echo "Required cache path is not a mounted filesystem: ${p}" >&2
            exit 1
          fi
        done

    - id: pacman-cache-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: arch-pacman-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-${{ inputs.cache-epoch }}
        restore-keys: |
          arch-pacman-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-
          arch-pacman-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-
        path: |
          /var/cache/pacman/pkg
          /etc/pacman.d/gnupg

    - id: yay-cache-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: arch-yay-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-${{ inputs.cache-epoch }}
        restore-keys: |
          arch-yay-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-
          arch-yay-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-
        path: /home/builder/.cache/yay

    - id: mise-cache-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: arch-mise-v3-${{ hashFiles(inputs.mise-config-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-${{ inputs.cache-epoch }}
        restore-keys: |
          arch-mise-v3-${{ hashFiles(inputs.mise-config-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-
          arch-mise-v3-${{ hashFiles(inputs.mise-config-path) }}-
        path: |
          /home/builder/.local/share/mise
          /home/builder/.cache/mise
          /home/builder/.local/state/mise

    - name: System bootstrap (root)
      shell: bash
      run: |
        set -euo pipefail
        pacman-key --init
        pacman-key --populate archlinux
        pacman -Syu --noconfirm archlinux-keyring
        pacman -S --needed --noconfirm base-devel git zsh sudo util-linux curl ca-certificates tar gzip pacman-contrib

    - name: Install pinned chezmoi
      shell: bash
      run: |
        set -euo pipefail
        version="${{ inputs.chezmoi-version }}"
        archive="chezmoi_${version}_linux_amd64.tar.gz"
        checksums="chezmoi_${version}_checksums.txt"

        tmpdir="$(mktemp -d)"
        trap 'rm -rf "${tmpdir}"' EXIT

        curl -fsSLo "${tmpdir}/${archive}" "https://github.com/twpayne/chezmoi/releases/download/v${version}/${archive}"
        curl -fsSLo "${tmpdir}/${checksums}" "https://github.com/twpayne/chezmoi/releases/download/v${version}/${checksums}"

        grep "  ${archive}$" "${tmpdir}/${checksums}" | (cd "${tmpdir}" && sha256sum -c -)
        tar -xzf "${tmpdir}/${archive}" -C "${tmpdir}" chezmoi

        install -m 0755 "${tmpdir}/chezmoi" /usr/local/bin/chezmoi
        chezmoi --version

    - name: Create builder user
      shell: bash
      run: |
        set -euo pipefail
        if ! id builder >/dev/null 2>&1; then
          useradd --uid 1000 --create-home builder
        fi
        echo 'builder ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/builder
        chown -R builder:builder "$GITHUB_WORKSPACE"

    - name: Prepare builder home
      shell: bash
      run: |
        set -euo pipefail
        sudo -u builder install -d \
          /home/builder/.cache \
          /home/builder/.local

    - name: Fix cache permissions (builder)
      shell: bash
      run: sudo chown -R builder:builder /home/builder || true

    - name: Apply chezmoi (builder)
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail
        sudo -Hu builder env GITHUB_TOKEN="${GITHUB_TOKEN}" \
          chezmoi init --apply -S "${GITHUB_WORKSPACE}"

    - name: Trim caches (warm mode)
      if: inputs.warm-mode == 'true'
      shell: bash
      run: |
        set -euo pipefail
        paccache --noconfirm -rk1
        paccache --noconfirm -ruk0
        sudo -u builder yay -Sc --noconfirm

    - name: Save pacman cache
      if: success() && github.event_name != 'pull_request'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: arch-pacman-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-${{ inputs.cache-epoch }}
        path: |
          /var/cache/pacman/pkg
          /etc/pacman.d/gnupg

    - name: Save yay cache
      if: success() && github.event_name != 'pull_request'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: arch-yay-v3-${{ hashFiles(inputs.arch-extra-packages-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-${{ inputs.cache-epoch }}
        path: /home/builder/.cache/yay

    - name: Save mise cache
      if: success() && github.event_name != 'pull_request'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: arch-mise-v3-${{ hashFiles(inputs.mise-config-path) }}-${{ inputs.warm-mode == 'true' && 'warm' || 'build' }}-${{ inputs.cache-epoch }}
        path: |
          /home/builder/.local/share/mise
          /home/builder/.cache/mise
          /home/builder/.local/state/mise
