name: Arch Linux
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: System bootstrap (root)
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm base-devel git zsh sudo util-linux

      - name: Create builder user
        run: |
          useradd --uid 1000 --create-home builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Restore caches
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/pacman/pkg
            /etc/pacman.d/gnupg
            /home/builder/.cache/yay
            /home/builder/.local/share/mise
            /home/builder/.cache/mise
          key: |
            ${{ runner.os }}-dotfiles-${{ hashFiles('dot_config/yay/extra-packages', 'dot_config/mise/config.toml') }}
          restore-keys: |
            ${{ runner.os }}-dotfiles-

      - name: Fix cache permissions (builder)
        run: sudo chown -R builder:builder /home/builder/.cache /home/builder/.local || true

      - name: Apply chezmoi (builder)
        shell: 'script -q -e -c "bash {0}"'
        run: |
          sudo --preserve-env=GITHUB_TOKEN -Hu builder \
            zsh -c "$(curl -fsLS https://chezmoi.io/get)" -- init --apply -S .
