name: Arch Linux
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Cache pacman/yay
      uses: actions/cache@v3
      with:
        key: arch-pkg-${{ hashFiles('dot_config/yay/extra-packages') }}
        restore-keys: arch-pkg-
        # pacman と yay を同じホスト側ディレクトリにまとめる
        path: |
          ~/arch-cache/pacman-pkg        # /var/cache/pacman/pkg にマウント
          ~/arch-cache/yay               # ~/.cache/yay にマウント

    - name: Cache mise
      uses: actions/cache@v3
      with:
        key: arch-mise-${{ hashFiles('dot_config/mise/config.toml') }}
        restore-keys: arch-mise-
        path: |
          ~/.cache/mise
          ~/.local/share/mise

    - name: Build arch image
      run: docker build -t ${{ steps.image_tag.outputs.TAG }} images/arch

    - name: Run arch container
      run: |
        sudo chown -R 1000:1000 ${{ github.workspace }}
        docker run --rm -t \
          -v ${{ github.workspace }}:/home/user \
          -v ~/arch-cache/pacman-pkg:/var/cache/pacman/pkg \
          -v ~/arch-cache/yay:/home/user/.cache/yay \
          -v ~/.cache/mise:/home/user/.cache/mise \
          -v ~/.local/share/mise:/home/user/.local/share/mise \
          -w /home/user \
          ${{ github.sha }}-arch \
          zsh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
