name: Arch Linux
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache yay
        uses: actions/cache@v3
        with:
          key: arch-yay-${{ hashFiles('dot_config/yay/extra-packages') }}
          restore-keys: arch-yay-
          path: |
            ~/.cache/yay

      - name: Cache mise
        uses: actions/cache@v3
        with:
          key: arch-mise-${{ hashFiles('dot_config/mise/config.toml') }}
          restore-keys: arch-mise-
          path: |
            ~/.cache/mise
            ~/.local/share/mise

      - name: Create image tag
        id: image_tag
        run: |
          VARIANT="$(TZ=UTC-9 date +%Y%m%d)_${IMAGE_HASH:0:7}"
          IMAGE_NAME="onlymyarch"
          TAG="${IMAGE_NAME}:${VARIANT}"
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Build arch image
        run: |
          docker build -t ${{ steps.image_tag.outputs.TAG }} images/arch

      - name: Run arch container
        run: |
          # Change owner of workspace to ubuntu user
          sudo chown -R 1000:1000 ${{ github.workspace }}
          docker run -t --rm  \
            -v ${{ github.workspace }}:/home/user \
            -v ${{ env.HOME }}/.cache/mise:/home/user/.cache/mise \
            -v ${{ env.HOME }}/.local/share/mise:/home/user/.local/share/mise \
            -v ${{ env.HOME }}/.cache/yay:/home/user/.cache/yay \
            -w /home/user \
            ${{ steps.image_tag.outputs.TAG }} zsh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
