name: Arch Linux
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: System bootstrap (root)
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Sy --noconfirm base-devel git sudo curl gnupg zsh

      - name: Create builder user
        run: |
          useradd --uid 1000 --create-home builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Restore caches
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/pacman/pkg
            /etc/pacman.d/gnupg
            /home/builder/.cache/yay
            /home/builder/.local/share/mise
            /home/builder/.cache/mise
          key:
            ${{ runner.os }}-dotfiles-${{ hashFiles('dot_config/yay/extra-packages',
            'dot_config/mise/config.toml') }}
          restore-keys: ${{ runner.os }}-dotfiles-

      - name: Apply chezmoi (builder)
        run: |
          sudo --preserve-env=GITHUB_TOKEN -Hu builder bash -euo pipefail -c '
            mkdir -p ~/.config/yay
            [[ -f ~/.config/yay/config.json ]] || \
              yay --save --answerdiff None --answerclean None --sudoloop --removemake
            zsh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
          '
