name: Arch Linux
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      # options: --user 1000:1000

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore pacman & yay cache
        id: pacman-cache
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/pacman/pkg
            /etc/pacman.d/gnupg
            ~/.cache/yay
          key: |
            ${{ runner.os }}-pacman-yay-${{ hashFiles('dot_config/yay/extra-packages') }}
          restore-keys: |
            ${{ runner.os }}-pacman-yay-

      - name: Restore mise cache
        id: mise-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/mise
            ~/.cache/mise
          key: |
            ${{ runner.os }}-mise-${{ hashFiles('dot_config/mise/config.toml') }}
          restore-keys: |
            ${{ runner.os }}-mise-

      - name: pacman key init & system update
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Sy --noconfirm zsh base-devel

      - name: Apply chezmoi
        run: |
          zsh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
