name: Arch Linux
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    container:
      image: archlinux:latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: System bootstrap (root)
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm base-devel git zsh sudo util-linux

      - name: Create builder user
        run: |
          useradd --uid 1000 --create-home builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/builder
          chown -R builder:builder "$GITHUB_WORKSPACE"

      - name: Prepare builder home
        run: sudo -u builder install -d \
          /home/builder/.cache \
          /home/builder/.local

      - name: Restore pacman cache
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/pacman/pkg
            /etc/pacman.d/gnupg
          key: ${{ runner.os }}-pacman-${{ hashFiles('dot_config/yay/extra-packages') }}
          restore-keys: ${{ runner.os }}-pacman-

      - name: Restore yay cache
        uses: actions/cache@v3
        with:
          path: /home/builder/.cache/yay
          key: ${{ runner.os }}-yay-${{ hashFiles('dot_config/yay/extra-packages') }}
          restore-keys: ${{ runner.os }}-yay-

      - name: Restore mise cache
        uses: actions/cache@v3
        with:
          path: |
            /home/builder/.local/share/mise
            /home/builder/.cache/mise
            /home/builder/.local/state/mise
          key: ${{ runner.os }}-mise-${{ hashFiles('dot_config/mise/config.toml') }}
          restore-keys: ${{ runner.os }}-mise-

      - name: Fix cache permissions (builder)
        run: sudo chown -R builder:builder /home/builder || true

      - name: Apply chezmoi (builder)
        shell: 'script -q -e -c "bash {0}"'
        run: |
          sudo --preserve-env=GITHUB_TOKEN -Hu builder \
            zsh -c "$(curl -fsLS https://chezmoi.io/get)" -- init --apply -S .
