name: Mac - Clean Build and Warm Cache
on:
  push:
    branches: [main]

  schedule:
    - cron: "17 10 * * 6"

jobs:
  warm:
    uses: ./.github/workflows/mac-build.yaml
    with:
      force-refresh: true
