name: Mac
on: pull_request
jobs:
  dotfiles:
    runs-on: macos-latest
    timeout-minutes: 180

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 自動更新抑制
      HOMEBREW_NO_AUTO_UPDATE: "1"

    steps:
      - uses: actions/checkout@v3

      - name: Cache Homebrew downloads
        uses: actions/cache@v3
        with:
          key: macos-brew-${{ hashFiles('dot_config/homebrew/Brewfile') }}
          restore-keys: macos-brew-
          path: ~/Library/Caches/Homebrew

      - name: Cache Homebrew Cellar & Opt
        uses: actions/cache@v3
        with:
          key: macos-brew-cellar-${{ hashFiles('dot_config/homebrew/Brewfile') }}
          restore-keys: macos-brew-cellar-
          path: |
            /usr/local/Homebrew/Cellar
            /usr/local/Homebrew/opt

      - name: Update Homebrew once
        run: brew update --preinstall --quiet

      - name: Install dotfiles
        run: |
          /bin/zsh -c "$(curl -fsSL chezmoi.io/get)" -- init --apply -S .
