name: Mac
on: pull_request
jobs:
  dotfiles:
    runs-on: macos-latest
    timeout-minutes: 180

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOMEBREW_BUNDLE_BREW_SKIP: "awscli"

    steps:
      - uses: actions/checkout@v3

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          key: macos-brew-${{ hashFiles('Brewfile') }}
          restore-keys: macos-brew-
          path:
            - ${{ env.HOME }}/Library/Caches/Homebrew
            - ${{ env.HOME }}/.cache/Homebrew

      - name: Cache mise
        uses: actions/cache@v3
        with:
          key: macos-mise-${{ hashFiles('.config/mise/config.toml') }}
          restore-keys: macos-mise-
          path:
            - ${{ env.HOME }}/.cache/mise
            - ${{ env.HOME }}/.local/share/mise

      - name: Install dotfiles
        run: |
          brew upgrade
          /bin/zsh -c "$(curl -fsSL chezmoi.io/get)" -- init --apply -S .

      - name: Debug cache dirs
        if: always()
        run: |
          echo '--- Brew cache ---'
          ls -al $HOME/Library/Caches/Homebrew
          echo '--- mise cache ---'
          ls -al $HOME/.cache/mise
          ls -al $HOME/.local/share/mise
