name: build

on:
  push:
    branches: [device/mac]

jobs:
  dotfiles:
    runs-on: macos-14
    timeout-minutes: 180
    env:
      HOMEBREW_BUNDLE_BREW_SKIP: "awscli"

    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: |
          brew upgrade

          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .

          brew uninstall --force $(brew list)
