name: Mac
on:
  push:
    branches: [main]
  pull_request:

jobs:
  dotfiles:
    runs-on: macos-latest
    timeout-minutes: 60

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOMEBREW_BUNDLE_BREW_SKIP: awscli
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_BUNDLE_NO_UPGRADE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mac
