[theme]
border = "blue"
selected-fg = "black"
selected-bg = "cyan"
description = "dark-grey"
filter = "green"
candidate = "white"

[abbreviations]
g = 'git'
gcd = 'cd $(git rev-parse --show-toplevel)'
gs = 'git status'
ga = 'git add'
gap = 'git add -p'
gd = 'git diff'
gl = 'git log --oneline'
gp = 'git pull'
gpo = 'git push origin HEAD'
gpf = 'git push --force-with-lease --force-if-includes origin HEAD'
gb = 'git branch'
gc = 'git checkout'
gf = 'git fetch'
gr = 'git rebase'
gsw = 'git switch'
gst = 'git stash'
dcu = 'docker compose up -d'
dcd = 'docker compose down'
dps = 'docker ps'
tf = 'terraform'
tfi = 'terraform init'
tfp = 'terraform plan -lock=false'
tfa = 'terraform apply'
tfd = 'terraform destroy'
tff = 'terraform fmt'
tfv = 'terraform validate'
tfo = 'terraform output'
tfsl = 'terraform state list'
tfss = 'terraform state show'
tfw = 'terraform workspace'
tfwl = 'terraform workspace list'
tfpl = 'terraform providers lock -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64 -platform=darwin_arm64 -platform=linux_arm64'
ca = 'cargo'
cab = 'cargo build'
car = 'cargo run'
cate = 'command -v cargo-nextest >/dev/null && cargo nextest run || cargo test'
cac = 'cargo check'
caf = 'cargo fmt'
cacl = 'cargo clippy'
caa = 'cargo add'
caw = 'cargo watch'
uv = 'uv'
uvr = 'uv run'
uva = 'uv add'
uvs = 'uv sync'
uvl = 'uv lock'
uvv = 'uv venv'
uvpi = 'uv pip install'
t = 'tmux'
ta = 'tmux a'
tn = 'tmux new -A -s $(whoami)'
tks = 'tmux kill-session -a'
tkw = 'tmux kill-window -a'
tkp = 'tmux kill-pane -a'
mkdir = 'mkdir -p'
c = 'clear'
e = 'exit'
rm = 'trash-put'
v = 'nvim'
m = 'memo'
up = 'if [[ "$OSTYPE" == darwin* ]]; then brew upgrade && brew upgrade --cask --greedy && mas upgrade; else yay --noconfirm; fi && rustup update && mise cache clear && mise up && nvim --headless "+Lazy! update" +qa'
sz = 'source ~/.zshenv && source "${ZDOTDIR:-$HOME/.config/zsh}/.zshrc"'
ez = 'exec zsh -l'
ls = 'eza --icons --group-directories-first'
l = 'eza --icons --group-directories-first -l --header --git --group'
la = 'eza --icons --group-directories-first -a'
lt = 'eza --icons --group-directories-first --tree'
lla = 'eza --icons --group-directories-first -la --header --git --group'
b = 'bat --theme ansi'
cat = 'bat --theme ansi'
ch = 'chezmoi'
cha = 'chezmoi apply'
chd = 'chezmoi diff'
che = 'chezmoi edit'
chcd = 'cd $(chezmoi source-path)'

[[abbreviation]]
trigger = "gcm"
expansion = "git commit -m '{{cursor}}'"
description = "git commit with a message"
